server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: SELECT 1 FROM DUAL
      #      validation-query: SELECT  1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

mybatis:
  config-location: classpath:/mybatis/config/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

mapper:
  mappers: com.security.common.core.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

aliyun:
  accessKeyId:
  accessKeySecret:
  signName:
  defaultConnectTimeout: 10000
  defaultReadTimeout: 10000
  templateCodeRegist:

email:
  protocol: SMTP
  port: 465
  from:
  user:
  authCode:
  mailHost: smtp.exmail.qq.com
  mailContent: 您的验证码为%s,有效期为%s分钟,超过有效期您需要重新申请忘记密码操作！
  validate: 5
  title: 验证码

wechat:
  client:
    clientId:
    clientSecret:

dingding:
  client:
    clientId:
    clientSecret:

feishu:
  client:
    clientId:
    clientSecret:

callback:
  domain:

